# Generated by Django 3.2.14 on 2022-08-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licznik', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klasa',
            name='name',
            field=models.CharField(max_length=100, verbose_name='klasa'),
        ),
        migrations.AlterUniqueTogether(
            name='klasa',
            unique_together={('name', 'school')},
        ),
    ]
