# Generated by Django 3.2.14 on 2022-08-21 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('licznik', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='klasa',
            name='school',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='licznik.school'),
        ),
    ]
