# Generated by Django 3.2.14 on 2022-08-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licznik', '0002_auto_20220823_1717'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='klasa',
            constraint=models.UniqueConstraint(fields=('name', 'school'), name='unique_name_school'),
        ),
    ]
