# Generated by Django 3.2.14 on 2022-08-23 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licznik', '0003_klasa_unique_name_school'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='klasa',
            unique_together=set(),
        ),
    ]
