# Generated by Django 3.2.14 on 2022-09-09 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('licznik', '0003_alter_klasa_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kandydat',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kandydat'),
        ),
        migrations.AlterField(
            model_name='klasa',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licznik.school', verbose_name='szkoła'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Wymagany', max_length=254, unique=True, verbose_name='email adress'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Wpisz unikalną nazwę', max_length=30, unique=True, verbose_name='Nazwa użytkownika'),
        ),
    ]
