# Generated by Django 3.2.14 on 2022-09-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licznik', '0004_auto_20220909_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Unikalna nazwa', max_length=30, unique=True, verbose_name='Nazwa użytkownika'),
        ),
    ]
