# Generated by Django 3.2.14 on 2022-09-25 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('licznik', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kandydat',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik'),
        ),
    ]
