# Generated by Django 3.2.14 on 2022-09-30 15:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licznik', '0006_alter_kandydat_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(help_text='Plik powinien zawierać w odpowiedniej kolejności: hasło, login, pierwsze i drugie imię, nazwisko, email oraz pesel', upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])], verbose_name='Dołącz plik csv'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('username', 'pesel', 'email'), name='unique User'),
        ),
    ]
