# Generated by Django 3.2.14 on 2022-09-30 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licznik', '0007_auto_20220930_1517'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
