# Generated by Django 3.2.14 on 2022-09-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licznik', '0008_alter_user_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Wymagany', max_length=254, null=True, unique=True, verbose_name='email adress'),
        ),
    ]
