# Generated by Django 3.2.14 on 2022-09-30 15:43

import django.core.validators
from django.db import migrations, models
import licznik.models


class Migration(migrations.Migration):

    dependencies = [
        ('licznik', '0009_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pesel',
            field=models.CharField(help_text='Wymagany', max_length=11, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(11), licznik.models.f_pesel]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Unikalna nazwa', max_length=30, null=True, unique=True, verbose_name='Nazwa użytkownika'),
        ),
    ]
