# Generated by Django 3.2.14 on 2022-10-07 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licznik', '0013_auto_20220930_1600'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
