# Generated by Django 3.2.14 on 2022-10-07 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licznik', '0014_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
