# Generated by Django 3.2.14 on 2022-10-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licznik', '0015_alter_user_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Unikalna nazwa', max_length=30, verbose_name='Nazwa użytkownika'),
        ),
    ]
